### ISSUE TITLE
Relative URLs in included content should be made absolute

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#16]
Say some included content contains relative URLs such as the following:

```
<a href="rel/path/to/other-page.html">Other page</a>
<img src="my-images/img.jpg" />
```

Should the respective `@href` and `@src` be relative to the including page or the included content? 
I think it is the included content. This will require absolutizing relative URLs based on the URL of the included content before inserting.

**Comment by gustafnk** [comment]
Good idea. I plan to expose a hook for transforming the DOM before insertion (https://github.com/gustafnk/h-include/issues/17) and I think that such transformation could be exactly what you describe.

Thanks for submitting issue and thinking about this project by the way. I try to keep up, but it's currently quite busy unfortunately.

**Comment by gustafnk** [comment]
With https://github.com/gustafnk/h-include/pull/21 it's possible for a user to do this in a hook. Also, I think it's a hard general problem to solve, but there might be special cases that are easier for specific user scenarios.
