### ISSUE TITLE
Update contents in respone to @src changes

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#2]
Currently the contents installed into the `<h-include>` only match the `@src` URL at the moment the custom-element binding is attached. If the binding could listen for changes to `@src` and update the contents accordingly then `<h-include>` could be used something like a light-weight `<iframe>`.

**Comment by gustafnk** [comment]
https://github.com/gustafnk/h-include/pull/12/commits/51f0f533e7e4d7a8d0c63f8a0e95d3b9de1d1c16

@shogun70 What do you think?
