### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by gustafnk** [gustafnk/h-include#22]
(From https://github.com/gustafnk/h-include/issues/20#issue-155178318)
- basically any place in show_content() which returns or throws before the bottom of the function.
- fragment not found errors log a console warning but don't change the <h-include> class or content.
  Some user-interaction might have triggered a @src change but the contents and appearance 
  still matches the previous @src. 
  I wonder if this should be considered a 404 error?
- recursion error (maybe a 412 error is appropriate?)

**Comment by shogun70** [comment]
Also note that if show_content() throws then show_buffered_content() will not complete, potentially leaving `<h-include>` elements empty or with stale content.

**Comment by gustafnk** [comment]
@shogun70 What do you think of this? https://github.com/gustafnk/h-include/commit/b0c053012a9e0c93ed4ec154e3030c89e0876e14

**Comment by shogun70** [comment]
Actually I prefer the throw / try / catch approach in general. I was thinking to maybe put a try / catch around `show_content()`. 

See https://github.com/shogun70/h-include/blob/transform/h-include.js#L172 for an example.

**Comment by gustafnk** [comment]
Force pushed https://github.com/gustafnk/h-include/commit/4bfa77c97d7ba0a6185441059f5c2776a2be72e8 to same branch

**Comment by gustafnk** [comment]
Fixed point "basically any place in show_content() which returns or throws before the bottom of the function." in https://github.com/gustafnk/h-include/pull/36

**Comment by gustafnk** [comment]
@shogun70 Do you think it would be enough to add an 'error' class to the @src attribute when an include fails? In that case, the user could choose to style the `h-include` element differently then.

**Comment by shogun70** [comment]
Just to clarify: 
Instead of

``` .html
<h-include src="..." class="included include_200">
```

you would get 

``` .html
<h-include src="..." class="error">
```

**Comment by gustafnk** [comment]
Oh, sorry for the typo. I meant the @class attribute.

Yes, you're correct. What do you think?

**Comment by shogun70** [comment]
It would be good if we could also do this for errors in `include()`: data-URIs, etc.

**Comment by gustafnk** [comment]
This issue was opened a long time ago, but I believe it's mostly fixed.

Closing. Feel free to re-open.
