### ISSUE TITLE
Expose `proto` as the externally accessible `hinclude.prototype`

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#27]
This will allow other other custom-elements to inherit from hinclude, 
as well as allowing page authors to define global hooks, for example

``` .js
hinclude.prototype.extractFragment = function(container) {
    var mode = this.getAttribute('mode');
    // choose different pre-processing based on "mode"
   return newContainer;
}
```

**Comment by gustafnk** [comment]
I really like this idea 👍

**Comment by gustafnk** [comment]
@shogun70 If you have any code that fixes this issue, I'd be happy to review it and merge.

(My time is extremely limited right now, unfortunately)

**Comment by gustafnk** [comment]
@shogun70 Something like this? https://github.com/gustafnk/h-include/commit/8c6f1048295a96ca7ffc9aae7df166906c994099

(Exposing element rather than prototype)

**Comment by gustafnk** [comment]
@shogun70 I just realised I completely misunderstood your issue. The above branch was for being able to extending the h-include custom element.

**Comment by gustafnk** [comment]
Or, maybe I just misunderstood your need, you're talking about overriding global functionality and I'm talking about inheriting from the custom element. The above branch should satisfy both need though, I think.

**Comment by shogun70** [comment]
Would you consider renaming `hinclude` to `HIncludeElement` (or just exposing the prototype on `hinclude`).

Something like:

``` .js
HIncludeElement = document.registerElement('h-include', {
    prototype: Object.create(HTMLElement.prototype)
});
Object.assign(HIncludeElement, { /* static methods */});
Object.assign(HIncludeElement.prototype, { /* instance methods */});
```

**Comment by gustafnk** [comment]
Yes, that looks good. Object.assign is in ES6, so I need to do it more imperatively, I think.

Not sure how to deal with the versioning of this though. My current thought: the `<h-include>` should always work as before (otherwise, bump major version). If the hooks API changes, I will just bump minor (since right now, the number of users for the hooks is quite small).

**Comment by gustafnk** [comment]
@shogun70 I did a major change and I'm quite satisfied with it :) https://github.com/gustafnk/h-include/commit/54c1af7eb8734825daaf4b51a615b2499fbc7955 Could you please have a look?

**Comment by shogun70** [comment]
Looks good - do you think `include()` or `checkRecursion()` should be exposed on `prototype`? Can external code usefully call or over-ride them?

**Comment by gustafnk** [comment]
Good point, I'll move `include` and `checkRecursion` to the static methods.

**Comment by gustafnk** [comment]
@shogun70 Fixed in https://github.com/gustafnk/h-include/commit/851ca12699047845f14da27986c2f1878deb88cc

**Comment by gustafnk** [comment]
Fixed with merge of https://github.com/gustafnk/h-include/pull/35
