### ISSUE TITLE
Hook calling conventions

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#28]
If I have `hincElement` which is a reference to a `<h-include>` element, and I define a hook such as

``` .js
hincElement.createContainer = function(req) {
    var mode = this.getAttribute('mode');
    // Implement "mode" dependent behavior
    ...
   return container;
}
```

then in my hook `this` should refer to the `<h-include>` element. 
Hooks which are present on the element should be called similar to:

``` .js
element[hookName](args)
```

**If the hook is matched by a static method** on `hinclude` (e.g. `createContainer -> create_container`) then for consistency the static method should be passed the element as the first argument:

``` .js
hinclude[hook_name](element, args...)
```

**Comment by gustafnk** [comment]
What do you mean with this? "Hooks which are present on the element should be called similar to"

Where?

**Comment by gustafnk** [comment]
I want to remove all static default hooks and just making them functions on the element (if possible). This will uniform the behaviour for external and internal hooks.

**Comment by shogun70** [comment]
Yes, replacing the static default hooks with functions on the element should address this. For example:

Current implementation for calling createContainer is:

``` .js
var createContainer = element.createContainer || hinclude.create_container;
var container = createContainer(req);
```

If there is a `createContainer` method on the element then this is equivalent to:

``` .js
var container = element.createContainer.call(window, req);
```

and thus the `createContainer` method has no way to access the element.

This will be fixed if the method is called with 

``` .js
var container = element.createContainer(req)
```

**Comment by gustafnk** [comment]
Proposed solution in https://github.com/gustafnk/h-include/commit/54c1af7eb8734825daaf4b51a615b2499fbc7955

**Comment by gustafnk** [comment]
Fixed with https://github.com/gustafnk/h-include/pull/35
