### ISSUE TITLE
data URIs don't trigger onEnd

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#29]

**Comment by gustafnk** [comment]
Hmm, what's your use-case for using data URIs with h-include?

**Comment by shogun70** [comment]
I don't think there is a strong use-case. I'm using them when I want to grab different parts of the same included file to update different parts of the DOM. Something like:

``` .html
<h-include id="breadcrumbs"></h-include>
<div>other stuff</div>
<h-include id="content"></h-include>
<script>
var content = document.getElementById('content');
content.extractFragment = function(container, fragment) {
    var breadcrumbs = document.getElementById('breadcrumbs');
    var nav = hinclude.extract_fragment(container, 'nav');
    breadcrumbs.setAttribute('src', 'data:text/html,' + encodeURIComponent(nav.innerHTML));
    return hinclude.extract_fragment(container, fragment);
}
content.setAttribute('src', some_content_url);
</script>
```

There's other ways to satisfy this use-case and hinclude would be simpler if it just didn't support data-URIs. But if the support stays in then it should call `onEnd()`. And `extractFragment`, etc - definitely simpler to remove it as a supported scheme.

**Comment by gustafnk** [comment]
Right now, I think we should do a check for `data:` and throw a 'not supported' exception.

**Comment by gustafnk** [comment]
Closing this in favour of https://github.com/gustafnk/h-include/issues/31
