### ISSUE TITLE
Extract a fragment from the resource before inserting

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#3]
If there was a way to insert only a fragment of the intended included resource then `@src` could reference complete HTML pages rather than just partials. This might be modelled on the  `fragment` option in [jquery-pjax](https://github.com/defunkt/jquery-pjax#pjax-options) which can be set to a CSS selector.

**Comment by gustafnk** [comment]
https://github.com/gustafnk/h-include/pull/11

@shogun70 What do you think?

**Comment by gustafnk** [comment]
Did some other PRs that are based on https://github.com/gustafnk/h-include/pull/11. Will merge to master. 

We can always change the protocol before release, so not a big deal.

**Comment by gustafnk** [comment]
@shogun70 Feel free to review and reopen issue if solution is not inline with what you thought.

**Comment by gustafnk** [comment]
Improved in https://github.com/gustafnk/h-include/pull/21

**Comment by mnot** [comment]
Fragment inclusion seems cool, but if it crashes ie9, maybe not.

Other patch looks reasonable. Thanks!

**Comment by gustafnk** [comment]
@mnot Ok, I'll send the other patch as a PR and figure out a better way to implement fragment inclusion.
