### ISSUE TITLE
Needs recursion check

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#4]
If a HTML page uses h-include to include itself then the included contents will also initiate another include of itself and then another, ad infinitum.  For example:

``` html
<h-include src=""></h-include>
```

IMO a `<h-include>` instance should abort if it's `@src` is the same URL as one of its ancestor `<h-include>`s or the page URL.

**Comment by gustafnk** [comment]
https://github.com/gustafnk/h-include/pull/14

**Comment by shogun70** [comment]
I'm adding some files to demonstrate some different recursion scenarios:
- recursion.html
  recursion.html includes recursion.html
  This is currently detected and prevented with an error msg.
- recursion1.html
  recursion1.html includes recursion1a.html
  recursion1a.html then includes recursion1.html
- recursion2.html
  recursion2.html includes recursion2a.html
  recursion2a.html then includes recursion2b.html
  recursion2b.html then includes recursion2a.html

[recursion.zip](https://github.com/gustafnk/h-include/files/257062/recursion.zip)
