### ISSUE TITLE
Add note about http2

### ISSUE THREAD

**Issue by gustafnk** [gustafnk/h-include#7]

**Comment by ghost** [comment]
Any problem with using this with HTTP/2?...

**Comment by gustafnk** [comment]
No, on the contrary, I gets better with HTTP2, since Chrome (haven't tested other browsers for HTTP2) uses HTTP2 for ajax requests as well, so it reuses the connection for the ajax requests :)

**Comment by ghost** [comment]
Great to know! :)

Thank you.

**Comment by gustafnk** [comment]
Documented in https://github.com/gustafnk/h-include/pull/21
