### ISSUE TITLE
h-import: Invalid <link> and <script> elements aren't properly removed from url array 

### ISSUE THREAD

**Issue by kito99** [gustafnk/h-include#75]
Inside of `createContainer()` there is this code:

```javascript
var urls = importableElements.map(function(element) {
      if (element.tagName === 'SCRIPT') {
        return element.src;
      } else if (
          element.tagName === 'LINK' &&
          element.rel &&
          element.rel.toLowerCase() === 'stylesheet') {
        return element.href;
      }
    });
```
For `<link>` elements that don't have "rel="stylesheet", this leaves the value `undefined` in the array. When the `urls` list is passed to `loadjs`, this throws an exception. The `undefined` values should be removed from the array before calling `loadResources()`.

**Comment by gustafnk** [comment]
Thanks for the issue report!

Would you like to make a PR for this? (No tests needed for this)

**Comment by kito99** [comment]
I haven't tested it, but it certainly looks correct. Thanks!

**Comment by gustafnk** [comment]
Reproduced the error, verified the fix and refactored.

**Comment by gustafnk** [comment]
Fixed and released
