### ISSUE TITLE
Add success callback

### ISSUE THREAD

**Issue by gustafnk** [gustafnk/h-include#8]
From private conversation with @hallgren

**Comment by gustafnk** [comment]
Suggestion: https://github.com/gustafnk/h-include/pull/9

What do you think @hallgren?

**Comment by gustafnk** [comment]
To clarify, the way to set the onSuccess callback is done in JS, like:

```
var onSuccess = function(){
  // ...
}

var element = document.getElementsByTagName('h-include')[0];
element.onSuccess = onSuccess;
```

**Comment by hallgren** [comment]
To give some context to this issue. :)

I have played around with virtual doms and created a small library that takes a HTML string and updates a DOM element via a virtual dom. => https://github.com/hallgren/krumelur

The thing I would like to do is replace the `element.innerHTML = req.responseText` with a custom update function.

```
if (req.status === 200 || req.status === 304) {
  if (element.customUpdate) {
    element.customUpdate(req.responseText);
  }
  else {         
    element.innerHTML = req.responseText;
  }
  element.onSuccess && element.onSuccess();
```

This was just a thought and I´m not sure its in the scope of `h-include`.

**Comment by gustafnk** [comment]
@hallgren Ah, now I get it. Let me think about it.

**Comment by hallgren** [comment]
@gustafnk I created a PR #10 to have something to elaborate upon.

**Comment by gustafnk** [comment]
@hallgren 👍

**Comment by gustafnk** [comment]
I needed the onSuccess callback anyway and I created the issue for that. The solution is merged to master, so closing this issue.
