### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by ronnyfriedland** [gustafnk/h-include#84]
Hi, 
there is not LICENSE - file provided within the repository.
Under which license `h-include` is published? 

Kind regards,
Ronny

**Comment by gustafnk** [comment]
👋 The license is MIT. This information was only embedded in the h-include.js file itself, but I've added LICENSE.md for clarity (https://github.com/gustafnk/h-include/commit/af79cff5879c9c0ad992b1cacc4519e6117970d4).

Thanks for finding this! 🙏
