### ISSUE TITLE
Loading more than one resource fails

### ISSUE THREAD

**Issue by apatkinson** [gustafnk/h-include#93]
When loading more than one external resource there is unexpected behaviour:

#### JS
```javascript
require('h-include/lib/h-include');
require('h-include/lib/h-include-extensions');

window.addEventListener('load', function() {
    HInclude.initLazyLoad();
});
```
#### html:
```html
<h-include-lazy src="/returns-500" alt="/nice-error">loading</h-include-lazy><br>
<h-include-lazy src="/returns-500" alt="/nice-error">loading</h-include-lazy><br>
<h-include-lazy src="/returns-500" alt="/nice-error">loading</h-include-lazy>
```

#### Page output:
```
nice error
loading
loading
```

#### Page output:
```
nice error
nice error
nice error
```

**Comment by gustafnk** [comment]
Thanks a lot! I’ll try to have a look at this next week.

**Comment by gustafnk** [comment]
[Note to self] I've done some basic testing now and it seems like bug is not in the h-include-lazy, but in h-include itself.

**Comment by gustafnk** [comment]
Ugh, Travis has made a lot of changes this summer. This can take some time.....

**Comment by gustafnk** [comment]
I've decided to switch:
- from Travis to Github Actions (I just can't get the new Travis to work)
- from SauceLabs to BrowserStack

However, this is going to take some time, unless I get help.

@apatkinson I'm happy that you reported the bug! And, if you would like to accelerate and think you can help out, please do! :) I would be super grateful! (And I also understand if you don't have time, etc, of course)

**Comment by apatkinson** [comment]
What is it that you'd require help with? I have access to crossbrowsertesting.com if that help? Does the commit you did fix the issue?

**Comment by gustafnk** [comment]
Yes, the commit fixes the issue and according to my manual testing the fix doesn't break anything else. BUT, I'd like the build process to verify this as well.

I'd like to get help to automate browser testing using Github Actions, using BrowserStack or crossbrowsertesting.com . 

Maybe you can fork the repo and get it to work, and then we'll figure out a way to transfer. Or I can assign you to a fitting role in this repo.

Again, just let me know if you're not up for the task and I'll find another way forward. Might take some time though...

**Comment by gustafnk** [comment]
I've done some more thinking on this and I think the shortest path forward is to continue with SauceLabs, since we then can have the test framework code relatively stable: https://github.com/gustafnk/h-include/blob/master/__tests__/browser-test.js

And there seems to be a Github Action to "run SauceLabs" from a Github Action: https://github.com/saucelabs/sauce-connect-action

**Comment by gustafnk** [comment]
@apatkinson Hey, I just want to say that I've come pretty far now with Github Actions and SauceLabs. No additional help needed from you, but thanks a bunch anyway! :)

**Comment by apatkinson** [comment]
@gustafnk Awesome :+1:. I did ping my team to see if anyone had any time, but it seems that didn't come to fruition. Ping if you need reviews.

**Comment by gustafnk** [comment]
@apatkinson Thanks, I appreciate it :)

I'm now able to run tests on my local computer that connects to SauceLabs using their Sauce Connect. Latest Chrome, Firefox and Edge show no regression, so the code change should be good. However, some other browsers get timeout, but I think that is due timeout settings etc – I remember that the tests were a bit flaky before. I'll try to fix that, so that the build process is as deterministic as possible (or find a workaround).

**Comment by gustafnk** [comment]
Automated tests works for all "latest" browsers, but fails for older browsers. In both master and fix-multiple-alt-attributes, so there doesn't seem to be a regression for the code change, but it would be nice to also have stable tests before making a release.

@apatkinson Are you dependent on a fast fix for this?

**Comment by apatkinson** [comment]
> Are you dependent on a fast fix for this?

Nope, but "soon" would be preferable. Thanks for all the extra work that has gone on with this (even though it seemed like a small fix!)

**Comment by gustafnk** [comment]
Progress! :) https://github.com/gustafnk/h-include/pull/95

Now that testing works again (at least through my local dev machine, to SauceLabs), I can start to actually merge this bug fix reliably!

**Comment by gustafnk** [comment]
Merged https://github.com/gustafnk/h-include/pull/96 to `master`.

I'll cut a release tomorrow.

**Comment by apatkinson** [comment]
@gustafnk Thank you for this :+1:
